os: osx
osx_image: xcode11.3
language: node_js
node_js:
- 12.8.1
branches:
  only:
  - src
# before_install:
# - sudo apt-get install python-software-properties
# - curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
# - sudo apt-get install -y nodejs
addons:
  apt:
    update: true
install:
- yarn
script:
- npm run build
env:
  global:
  - GH_REF: https://github.com/tajoy/tajoy.github.io.git
before_deploy:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- echo "tajoy.net" > ./public/CNAME
deploy:
- provider: pages
  skip_cleanup: true
  local_dir: ./public
  target_branch: master
  github_token: $GITHUB_TOKEN
  keep_history: false
  on:
    branch: src
- provider: script
  skip_cleanup: true
  script: bash scripts/deploy.sh
  on:
    branch: src
