language: node
node:
- 12.8.1
branches:
  only:
  - src
before_install:
- sudo apt-get install python-software-properties
- curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
- sudo apt-get install -y nodejs
addons:
  apt:
    update: true
install:
- wget https://github.com/gohugoio/hugo/releases/download/v0.68.3/hugo_0.68.3_Linux-64bit.deb
- sudo dpkg -i hugo*.deb
- npm install
script:
- npm run build
# after_script:
# - cd ./public
# - git init
# - git config user.name "Tajoy"
# - git config user.email "tj328111241@gmail.com"
# - git commit -am "Update Blog By TravisCI With Build $TRAVIS_BUILD_NUMBER"
# - git push --force --quiet "https://$GITHUB_TOKEN@${GH_REF}" master:master
# - git push --quiet "https://$GITHUB_TOKEN@${GH_REF}" master:master --tags
env:
  global:
  - GH_REF: https://github.com/tajoy/tajoy.github.io.git
before_deploy:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- echo "tajoy.net" > ./public/CNAME
deploy:
- provider: pages
  skip_cleanup: true
  local_dir: ./public
  target_branch: master
  github_token: $GITHUB_TOKEN
  keep_history: false
  on:
    branch: src-hugo
- provider: script
  skip_cleanup: true
  script: bash scripts/deploy.sh
  on:
    branch: src-hugo
