
# 网站名称：鱼跃此时海
# 描述： 鱼跃此时海，花开彼岸天
# 网站地址：https://www.overme.cn/
# 头像：https://www.overme.cn/static/img/portrait.jpg


description = "鱼跃此时海，花开彼岸天"
headPic     = "https://www.overme.cn/static/img/portrait.jpg"
link        = "https://www.overme.cn/"
name        = "鱼跃此时海"
